"""init

Revision ID: 7edc22734820
Revises: 
Create Date: 2026-04-22 23:32:04.553368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edc22734820'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('peak_power_kw', sa.Float(), nullable=True),
    sa.Column('is_v2g', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charging_sessions_id'), 'charging_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_charging_sessions_vehicle_id'), 'charging_sessions', ['vehicle_id'], unique=False)
    op.create_table('v2g_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('energy_discharged_kwh', sa.Float(), nullable=True),
    sa.Column('compensation_earned_inr', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2g_sessions_id'), 'v2g_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_v2g_sessions_vehicle_id'), 'v2g_sessions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v2g_sessions_vehicle_id'), table_name='v2g_sessions')
    op.drop_index(op.f('ix_v2g_sessions_id'), table_name='v2g_sessions')
    op.drop_table('v2g_sessions')
    op.drop_index(op.f('ix_charging_sessions_vehicle_id'), table_name='charging_sessions')
    op.drop_index(op.f('ix_charging_sessions_id'), table_name='charging_sessions')
    op.drop_table('charging_sessions')
    # ### end Alembic commands ###
